### ISSUE TITLE
Issue with GCC 8.3 since v36

### ISSUE THREAD

**Issue by weeebell** [rollbear/trompeloeil#180]
Hi,

since v36 the following snippet does not compile with GCC 8.3 anymore (it still works with clang-9):

```
#include <catch2/catch.hpp>
#include <catch2/trompeloeil.hpp>

#include <QObject>

class Mock
{
public:
    MAKE_MOCK0(f, bool());
};

TEST_CASE("")
{
    Mock m;
    REQUIRE_CALL(m, f()).RETURN(true);
}
```
```
/usr/local/include/trompeloeil.hpp: In instantiation of ‘constexpr bool trompeloeil::is_null(const T&) [with T = bool]’:
/usr/local/include/trompeloeil.hpp:1274:16:   required from ‘void trompeloeil::print(std::ostream&, const T&) [with T = bool; std::ostream = std::basic_ostream<char>]’
/usr/local/include/trompeloeil.hpp:2962:14:   required from ‘T trompeloeil::trace_agent::trace_return(T&&) [with T = bool]’
/usr/local/include/trompeloeil.hpp:3104:45:   required from ‘Ret trompeloeil::trace_return(trompeloeil::trace_agent&, F&, P&) [with Ret = bool; F = ____C_A_T_C_H____T_E_S_T____1()::<lambda(auto:1&)>; P = std::tuple<>; <template-parameter-1-4> = void]’
/usr/local/include/trompeloeil.hpp:3128:44:   required from ‘trompeloeil::return_of_t<Sig> trompeloeil::return_handler_t<Sig, T>::call(trompeloeil::trace_agent&, trompeloeil::call_params_type_t<Sig>&) [with Sig = bool(); T = ____C_A_T_C_H____T_E_S_T____1()::<lambda(auto:1&)>; trompeloeil::return_of_t<Sig> = bool; trompeloeil::call_params_type_t<Sig> = std::tuple<>]’
/usr/local/include/trompeloeil.hpp:3123:5:   required from here
/usr/local/include/trompeloeil.hpp:1145:34: error: no matching function for call to ‘is_null(const bool&, tag)’
     return ::trompeloeil::is_null(t, tag{});
            ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
/usr/local/include/trompeloeil.hpp:1111:3: note: candidate: ‘template<class T> constexpr decltype ((t == nullptr)) trompeloeil::is_null(const T&, std::true_type)’
   is_null(
   ^~~~~~~
/usr/local/include/trompeloeil.hpp:1111:3: note:   template argument deduction/substitution failed:
/usr/local/include/trompeloeil.hpp: In substitution of ‘template<class T> constexpr decltype ((t == nullptr)) trompeloeil::is_null(const T&, std::true_type) [with T = bool]’:
/usr/local/include/trompeloeil.hpp:1145:34:   required from ‘constexpr bool trompeloeil::is_null(const T&) [with T = bool]’
/usr/local/include/trompeloeil.hpp:1274:16:   required from ‘void trompeloeil::print(std::ostream&, const T&) [with T = bool; std::ostream = std::basic_ostream<char>]’
/usr/local/include/trompeloeil.hpp:2962:14:   required from ‘T trompeloeil::trace_agent::trace_return(T&&) [with T = bool]’
/usr/local/include/trompeloeil.hpp:3104:45:   required from ‘Ret trompeloeil::trace_return(trompeloeil::trace_agent&, F&, P&) [with Ret = bool; F = ____C_A_T_C_H____T_E_S_T____1()::<lambda(auto:1&)>; P = std::tuple<>; <template-parameter-1-4> = void]’
/usr/local/include/trompeloeil.hpp:3128:44:   required from ‘trompeloeil::return_of_t<Sig> trompeloeil::return_handler_t<Sig, T>::call(trompeloeil::trace_agent&, trompeloeil::call_params_type_t<Sig>&) [with Sig = bool(); T = ____C_A_T_C_H____T_E_S_T____1()::<lambda(auto:1&)>; trompeloeil::return_of_t<Sig> = bool; trompeloeil::call_params_type_t<Sig> = std::tuple<>]’
/usr/local/include/trompeloeil.hpp:3123:5:   required from here
/usr/local/include/trompeloeil.hpp:1115:17: error: invalid operands of types ‘const bool’ and ‘std::nullptr_t’ to binary ‘operator==’
   -> decltype(t == nullptr)
               ~~^~~~~~~~~~
/usr/local/include/trompeloeil.hpp: In instantiation of ‘constexpr bool trompeloeil::is_null(const T&) [with T = bool]’:
/usr/local/include/trompeloeil.hpp:1274:16:   required from ‘void trompeloeil::print(std::ostream&, const T&) [with T = bool; std::ostream = std::basic_ostream<char>]’
/usr/local/include/trompeloeil.hpp:2962:14:   required from ‘T trompeloeil::trace_agent::trace_return(T&&) [with T = bool]’
/usr/local/include/trompeloeil.hpp:3104:45:   required from ‘Ret trompeloeil::trace_return(trompeloeil::trace_agent&, F&, P&) [with Ret = bool; F = ____C_A_T_C_H____T_E_S_T____1()::<lambda(auto:1&)>; P = std::tuple<>; <template-parameter-1-4> = void]’
/usr/local/include/trompeloeil.hpp:3128:44:   required from ‘trompeloeil::return_of_t<Sig> trompeloeil::return_handler_t<Sig, T>::call(trompeloeil::trace_agent&, trompeloeil::call_params_type_t<Sig>&) [with Sig = bool(); T = ____C_A_T_C_H____T_E_S_T____1()::<lambda(auto:1&)>; trompeloeil::return_of_t<Sig> = bool; trompeloeil::call_params_type_t<Sig> = std::tuple<>]’
/usr/local/include/trompeloeil.hpp:3123:5:   required from here
/usr/local/include/trompeloeil.hpp:1124:3: note: candidate: ‘template<class T> constexpr bool trompeloeil::is_null(const T&, std::false_type)’
   is_null(
   ^~~~~~~
/usr/local/include/trompeloeil.hpp:1124:3: note:   template argument deduction/substitution failed:
/usr/local/include/trompeloeil.hpp:1145:34: note:   cannot convert ‘tag{}’ (type ‘tag’ {aka ‘std::integral_constant<bool, true>’}) to type ‘std::false_type’ {aka ‘std::integral_constant<bool, false>’}
     return ::trompeloeil::is_null(t, tag{});
            ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
/usr/local/include/trompeloeil.hpp:1136:3: note: candidate: ‘template<class T> constexpr bool trompeloeil::is_null(const T&)’
   is_null(
   ^~~~~~~
/usr/local/include/trompeloeil.hpp:1136:3: note:   template argument deduction/substitution failed:
/usr/local/include/trompeloeil.hpp:1145:34: note:   candidate expects 1 argument, 2 provided
     return ::trompeloeil::is_null(t, tag{});
            ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
```

**Comment by rollbear** [comment]
Hrmm! I was sure I had succeeded in working around that gcc bug.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93043

I'll look into it.

**Comment by weeebell** [comment]
great, thanks!

**Comment by AndrewPaxie** [comment]
@weeebell : Would you provide just a little more information, please?

* Version of GCC: `g++ --version`.
* Is this compiler vendor-provided (which vendor) or locally built?
* Command line used to compile the failure case.
* Version of Catch2 used.
* Is `#include <QObject>` essential to the failure case?
* Is `#include <catch2/trompeloeil.hpp>` essential to the failure case?

That is, does this test program succeed or fail?

```cpp
#include <catch2/catch.hpp>
#include <trompeloeil.hpp>

class Mock
{
public:
    MAKE_MOCK0(f, bool());
};

TEST_CASE("")
{
    Mock m;
    REQUIRE_CALL(m, f()).RETURN(true);
}
```

Curiously, this test program succeeds on Godbolt with command line
`--std=c++14 -O3` when header are.

```cpp
#include <catch.hpp>
#include <https://raw.githubusercontent.com/rollbear/trompeloeil/v36/include/trompeloeil.hpp>
```

**Comment by weeebell** [comment]
It has to do with `#include <QObject>`. The following example also fails. If you omit QObject, it works.
`g++ --version: g++ (Debian 8.3.0-6) 8.3.0`

```
#include <trompeloeil.hpp>

#include <QObject>

class Mock
{
public:
    MAKE_MOCK0(f, bool());
};

int main()
{
    Mock m;
    REQUIRE_CALL(m, f()).RETURN(true);
    return 0;
}
```

```
/usr/bin/c++ -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -fPIC -o test.cpp.o -c test.cpp
```

**Comment by AndrewPaxie** [comment]
Reproduced the error using the reduced example and this version of GCC:

```bash
/usr/bin/c++ --version
c++ (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Running on Ubuntu 19.10 (Eoan Ermine)

`qt5base-dev` is `5.12.4+dfsg-4ubuntu1`.

So not GCC version 8.3 specific.

**Comment by AndrewPaxie** [comment]
Odd that in this test program, that

```cpp
static_assert(trompeloeil::is_null_comparable<bool>::value);
```

is satisfied!

Omit the `QObject` header and the static assertion fails.

One hypothesis is that QT has a global `operator==()` matching the
conditions being tested in `is_null_comparable`.

**Comment by AndrewPaxie** [comment]
Blame `QChar`?

**Comment by rollbear** [comment]
Yeah, it looks like it. I don't know what kind of evil the Qt developers have concocted here.

```Cpp
#include <QtCore/qchar.h>
#include <type_traits>
struct indirect_null {
  operator std::nullptr_t() const;
};

template <typename T, typename = void>
struct nulltest : std::false_type {};
template <typename T>
struct nulltest<T, std::void_t<decltype(std::declval<const T&>() == indirect_null{})>>
  : std::true_type {};

static_assert(!nulltest<bool>::value);
```

Comment out `#include <QtCore/qchar.h>` and it compiles.

There *are* a bunch of `operator==` overloads for `QChar` in namespace scope (they *really* should be friends inlined in the class decl to only be found via ADL, but ¯\_(ツ)_/¯ )

**Comment by rollbear** [comment]
It *might* be enough to change the equality test to make an indirection for the type compared with:

```Cpp
template <typename T>
struct indirect
{
  operator T() const;
};
```

and

```Cpp
  template <typename T>
  using is_null_comparable = is_equal_comparable<indirect<T>, indirect_null>;
```

Need to play a lot more with this. This is really complicated stuff.

**Comment by rollbear** [comment]
OK, there we have it. Here's a reproduction of what's happening.

```Cpp
#include <type_traits>
#include <string_view>
#include <string>

struct indirect_null {
    template <typename T, typename C, typename ... As>
    using memfunptr = T (C::*)(As...);

    template <typename T>
    operator T*() const;
    template <typename T, typename C>
    operator T C::*() const;
    template <typename T, typename C, typename ... As>
    operator memfunptr<T,C,As...>() const;
  operator std::nullptr_t() const;
};

struct QChar
{
  QChar();
  QChar(int);
#ifdef FRIEND
  friend bool operator==(QChar,QChar);
  friend bool operator==(QChar, std::nullptr_t);
  friend bool operator==(std::nullptr_t, QChar);
#endif
};
#ifndef FRIEND
bool operator==(QChar,QChar);
bool operator==(QChar, std::nullptr_t);
bool operator==(std::nullptr_t, QChar);
#endif


template <typename T, typename = void>
struct nulltest : std::false_type {};
template <typename T>
struct nulltest<T, std::void_t<decltype(std::declval<const T&>() == indirect_null{})>>
  : std::true_type {};

static_assert(!nulltest<bool>::value);
static_assert(nulltest<char*>::value);
static_assert(!nulltest<std::string_view>::value);
static_assert(!nulltest<std::string>::value);
```

_IF_ the Qt developers had chosen to make the operators friends of `QChar`, this would've been a non-issue, but they're freestanding functions in global namespace, so here we are.

Using the `indirect<T>`, from above, solves this issue, but fails a lot of other cases.

**Comment by rollbear** [comment]
I believe I have a fix now. Can you try out branch `nullptr_compare` @weeebell?

I added a stripped down type, similar to `QChar`, and its global overloads, to the self test program, and it exhibited the same bug. I then found a fix for gcc (clang is unaffected.) Unfortunately, it seems that also modern versions of MSVC suffers from the problem, and the fix only applies to gcc, so there's a bit more work needed.

I feel extremely uncomfortable with this fix, because I don't understand why it solves the problem.

**Comment by rollbear** [comment]
This fix works in compiler explorer, but it fails the Appveyor CI builds for newer MSVC compilers :-(

https://gcc.godbolt.org/z/mVYaW4

**Comment by AndrewPaxie** [comment]
I observe 8 test case failures running clang++-latest with the current unit tests,
implying we both need the fix and cannot have the fix. :-(

The best I had today was using these definitions

```cpp
  template <typename T>
  struct indirect
  {
    using U = detail::decay_t<T>;

    operator U() const;
  };

  template <typename T>
  using is_null_comparable = is_equal_comparable<indirect<T>, indirect_null>;
```

The decay allowed the user-defined conversion to compile when `T` was of array type.

In this case there were three test case failures in C++14 and above (with the
same test cases failing for the C++11-specific unit tests).  They are what I
call the "old friends":

```text
unique_ptr<>() value when equal ptr deref expected is reported
test/compiling_tests_14.cpp:3064

unique_ptr<>() rvalue ref when equal ptr deref expected is reported
test/compiling_tests_14.cpp:3129

unique_ptr<>() const lvalue ref when equal ptr deref expected is reported
test/compiling_tests_14.cpp:3193
```

The mock functions with the issues are in class `C_ptr`:

```cpp
  MAKE_MOCK1(uptr, void(std::unique_ptr<int>));
  MAKE_MOCK1(uptrrr, void(std::unique_ptr<int>&&));
  MAKE_MOCK1(uptrcr, void(std::unique_ptr<int> const&));
```

I was left with the feeling that we could shape neither `indirect` nor `indirect_null`
into a robust solution, but I am ever the optimist and that the a teasing apart of
these failure cases may reveal a new way forward the will be broadly applicable
across our supported compilers.

**Comment by rollbear** [comment]
Is clang++-latest a home build from current master, or is it a clang-10 RC, or something else?

**Comment by AndrewPaxie** [comment]
Oops, sorry about the naming: `clang++-latest` is my name for clang trunk,
built daily, current commit `0e3a48778408b505946e465abf5c77a2ddd4918c`.

```bash
clang++-latest --version
```

```text
clang version 11.0.0 (https://github.com/llvm/llvm-project.git f60de4cdf7b8ca1b22700a6325a61a9b0da6a54b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
```

I compile Trompeloeil every day with GCC at HEAD and Clang at HEAD.

**Comment by rollbear** [comment]
;-)

Cool. I'll build it too and try. If it's a certain snapshot that fails, I'm not very worried, it's compiler work in progress after all. If it fails clang++10 RC, then I'm worried for real, especially since it's scheduled for release in a couple of weeks or so.

**Comment by rollbear** [comment]
clang-trunk @ 4ea8ed41356228834bdbd10c7e931c4488aaa680 correctly compiles and runs the self-test on branch `nulllptr_compare`. Now to check the release-10.x branch.

**Comment by rollbear** [comment]
As far as I've been able to check, this works also with clang 10.x branch, and gcc trunk. But MSVC fails, and my attempt to fix it didn't, and in addition it broke clang. More work needed, but as long as it's at all possible to fix for MSVC, we can handle it. What's another set of #ifdef's between friends? ¯\\_(ツ)_/¯

**Comment by AndrewPaxie** [comment]
After carefully checking out the `nullptr_compare` branch 3a34332,
I can confirm the regression tests for all supported GCC and Clang
configurations pass.

Will see whether the error messages from MSVC inspire any solutions.
This will be performed with Visual Studio Community 2019 version 16.4.4,
v142 (2019), v141 (2017), and then v140 (2015).

**Comment by rollbear** [comment]
My windows installation committed suicide (it failed to apply a security update, and then failed to revert, and then never booted again) so I currently don't have a working MSVC. Unfortunately developing through compiler explorer appears difficult, since the remaining MSVC issue is a run time error, and the MSVC compilers on CE don't allow for running the programs. I'll come up with something, but it may take a while.

**Comment by AndrewPaxie** [comment]
Tried about a dozen variations of `is_equal_comparable` and `indirect_null` for MSVC,
using the v142 platform.  All failed, but the closest was

```cpp
struct indirect_null
{
  template <typename T = std::nullptr_t>
  operator T() const;
};
```

and `is_null_comparable` defined as per the branch `nullptr_compare`.

With this modification to `nullptr_compare` (i.e. with `QCharIsh` code) only
test case `compiling_tests_11.cpp/4008-4021 failed, a familiar friend.

Of key interest to me was no need to declare

```cpp
  template <typename T>
  operator T&&() const = delete;
```

in `indirect_null`.

This is not of general use as by gaining back the ability to cope with
`QCharIsh` we lost ability to cope with `null_constructible`.

**Comment by rollbear** [comment]
I had a hunch, and it turned out to be correct. Only match the deleted conversion operator for types that are not constructible from `nullptr`.

```Cpp
struct indirect_null {
  template <
    typename T,
    typename = detail::enable_if_t<!std::is_constructible<T, std::nullptr_t>::value>
  >
  operator T&&() const = delete;
  operator std::nullptr_t() const;
};
```

My earlier reference to GCC bug 93043 is incorrect. This is an entirely different issue. I think this fix is important enough to warrant tagging a new release.

**Comment by rollbear** [comment]
I'm leaving the issue open until a release has been tagged.

**Comment by rollbear** [comment]
Fix is included in tagged release v37, so closing now.
