### ISSUE TITLE
Compilation Error with Clang when including QObject

### ISSUE THREAD

**Issue by reneme** [rollbear/trompeloeil#211]
As described in PR #210, we see a compilation error with clang 9 and 10 (and potentially other versions that we didn't try) after updating the library from v35 to v38. The error looks identical to the one tackled in #180. Note that applying the patch proposed in PR #210 fixes the compilation error. Attached is a minimal example to reproduce the issue.

## Minimal Code Example (`example.cpp`)

```C++
// If the `QObject` header is _not_ included the compilation error goes away
#include <QtCore/QObject>

class Foo {
  public:
    virtual void foo(const int someInt) = 0;
};

#define CATCH_CONFIG_MAIN
#include <catch2/catch.hpp>
#include <trompeloeil.hpp>

class FooMock : public Foo {
  public:
    MAKE_MOCK1(foo, void(const int), override);
};

TEST_CASE("Minimal example for GH #210")
{
    // The instantiation of `FooMock` is not required... the compile error
    // happens without it too.
    auto mock = std::make_unique<FooMock>();
    CHECK(mock);
}
```

### conanfile.txt
```
[requires]
catch2/2.12.3
trompeloeil/v38
qt/5.15.1@bincrafters/stable

[generators]
compiler_args
```

### Commands
```bash
conan install --build=missing .
clang++ -o example -std=C++17 @conanbuildinfo.args example.cpp
```

**Comment by rollbear** [comment]
Thank you. I will look into this tonight.

**Comment by reneme** [comment]
Great! Thank you. Let me know if I can assist somehow.

For completeness, here's what clang 10 came up with for the `example.cpp` on my machine:

```
In file included from example.cpp:10:
/Users/rmeusel/.conan/data/trompeloeil/v38/nexenio/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/trompeloeil.hpp:1207:12: error:
      no matching function for call to 'is_null'
    return ::trompeloeil::is_null(t, tag{});
           ^~~~~~~~~~~~~~~~~~~~~~
/Users/rmeusel/.conan/data/trompeloeil/v38/nexenio/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/trompeloeil.hpp:1336:9: note:
      in instantiation of function template specialization 'trompeloeil::is_null<int>' requested here
    if (is_null(t))
        ^
/Users/rmeusel/.conan/data/trompeloeil/v38/nexenio/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/trompeloeil.hpp:2941:20: note:
      in instantiation of function template specialization 'trompeloeil::print<int>' requested here
    ::trompeloeil::print(os, t);
                   ^
/Users/rmeusel/.conan/data/trompeloeil/v38/nexenio/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/trompeloeil.hpp:2952:55: note:
      in instantiation of function template specialization 'trompeloeil::missed_value<int>' requested here
    ::trompeloeil::ignore(std::initializer_list<int>{(missed_value(os, I, std::get<I>(t)),0)...});
                                                      ^
/Users/rmeusel/.conan/data/trompeloeil/v38/nexenio/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/trompeloeil.hpp:2961:5: note:
      in instantiation of function template specialization 'trompeloeil::stream_params<0, int &>' requested here
    stream_params(os, detail::make_index_sequence<sizeof...(T)>{}, t);
    ^
/Users/rmeusel/.conan/data/trompeloeil/v38/nexenio/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/trompeloeil.hpp:3094:5: note:
      in instantiation of function template specialization 'trompeloeil::stream_params<int &>' requested here
    stream_params(os, p);
    ^
/Users/rmeusel/.conan/data/trompeloeil/v38/nexenio/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/trompeloeil.hpp:4060:7: note:
      in instantiation of function template specialization 'trompeloeil::report_mismatch<void (int)>' requested here
      report_mismatch(e.active,
      ^
example.cpp:14:5: note: in instantiation of function template specialization 'trompeloeil::mock_func<false, void (int),
      int &>' requested here
    MAKE_MOCK1(foo, void(const int), override);
    ^
/Users/rmeusel/.conan/data/trompeloeil/v38/nexenio/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/trompeloeil.hpp:4929:35: note:
      expanded from macro 'MAKE_MOCK1'
#define MAKE_MOCK1                TROMPELOEIL_MAKE_MOCK1
                                  ^
/Users/rmeusel/.conan/data/trompeloeil/v38/nexenio/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/trompeloeil.hpp:4226:3: note:
      expanded from macro 'TROMPELOEIL_MAKE_MOCK1'
  TROMPELOEIL_MAKE_MOCK_(name,,1, __VA_ARGS__,,)
  ^
/Users/rmeusel/.conan/data/trompeloeil/v38/nexenio/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/trompeloeil.hpp:4438:27: note:
      expanded from macro 'TROMPELOEIL_MAKE_MOCK_'
    return ::trompeloeil::mock_func<trompeloeil_movable_mock, TROMPELOEIL_REMOVE_PAREN(sig)>( \
                          ^
/Users/rmeusel/.conan/data/trompeloeil/v38/nexenio/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/trompeloeil.hpp:1186:3: note:
      candidate function template not viable: no known conversion from 'integral_constant<[...],
      is_null_comparable<int>::value && !is_matcher<int>::value && !std::is_array<int>::value aka true>' to
      'integral_constant<[...], false aka false>' for 2nd argument
  is_null(
  ^
/Users/rmeusel/.conan/data/trompeloeil/v38/nexenio/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/trompeloeil.hpp:1173:3: note:
      candidate template ignored: substitution failure [with T = int]: invalid operands to binary expression
      ('const int' and 'nullptr_t')
  is_null(
  ^
/Users/rmeusel/.conan/data/trompeloeil/v38/nexenio/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/trompeloeil.hpp:1198:3: note:
      candidate function template not viable: requires single argument 't', but 2 arguments were provided
  is_null(
  ^
1 error generated.
```

**Comment by rollbear** [comment]
Just a short update to say that I have now reproduced it. There was a lot to download for someone who doesn't do GUI development. I shortened your program yet a bit:

```Cpp
// If the `QObject` header is _not_ included the compilation error goes away
#include <QtCore/QObject>
#include <trompeloeil.hpp>

class FooMock
{
  public:
  MAKE_MOCK1(foo, void(int));
};
```

I do wonder what kind of shenanigans the Qt developers have been up to, to make things break this way only by including a file. Probably some nasty templated operator in global namespace.

**Comment by rollbear** [comment]
OK, it's QChar and its operators. What's the purpose of the QT_BEGIN_NAMESPACE macro, since it seems to expand to nothing?
Anyway, I also see that your proposed fix works, at least for clang-10 and it doesn't break things for g++-10 either, so that is good. I just wart to add something similar to this in the test suite. The fact that the CI build worked for your PR (the g++-5 failure was some unrelated spurious network connection problem) makes me less nervous about this.

**Comment by rollbear** [comment]
As an aside, the "make hidden friends" idiom is a nice way to avoid these kinds of problems. I wish the Qt developers had known about it at the time (I appreciate that they cannot change this now without breaking tons of programs.)

https://www.justsoftwaresolutions.co.uk/cplusplus/hidden-friends.html

**Comment by rollbear** [comment]
Oh, nasty! It depends on the `#include` order. If you include `<trompeloeil.hpp>` before you include `<QtCore/qchar.h>`, then it compiles.

Recreated with a minimalized "QChar" type. https://godbolt.org/z/Y4Enqo

Now to figure out why my attempt to recreate in the self test suite fails.

**Comment by rollbear** [comment]
So, it's time to play the compiler quirk dance again.

My latest attempt works for all versions of gcc and clang, but only for older versions of MSVC. I do not have time to play with it further tonight. Should you wish to give it a shot, this "godbolt" link may be useful, although the tests there all work.

https://godbolt.org/z/vvsW6o

The failing MSVC builds are available from appveyor: https://ci.appveyor.com/project/rollbear/trompeloeil/builds/35625058

I have not had time to analyze those failures yet.

**Comment by reneme** [comment]
Derived from you godbolt link, I applied the following patch to the `v38` and can confirm that it works smoothly on our compiler-zoo.

```diff
diff --git a/include/trompeloeil.hpp b/include/trompeloeil.hpp
index f5923d4..6c4b29b 100644
--- a/include/trompeloeil.hpp
+++ b/include/trompeloeil.hpp
@@ -1131,7 +1131,7 @@ template <typename T>
 #if !TROMPELOEIL_CLANG
     template <
       typename T,
-      typename = detail::enable_if_t<!std::is_constructible<T, std::nullptr_t>::value>
+      typename = detail::enable_if_t<std::is_convertible<std::nullptr_t, T>::value>
     >
     operator T&&() const = delete;
 #endif
@@ -1166,7 +1166,7 @@ template <typename T>
   using is_null_comparable = is_equal_comparable<T, indirect_null>;
 #endif

-  template <typename T>
+  template <typename T, typename = decltype(std::declval<T const&>() == nullptr)>
   inline
   constexpr
   auto
@@ -1178,6 +1178,17 @@ template <typename T>
   {
     return t == nullptr;
   }
+  template <typename T, typename V>
+  inline
+  constexpr
+  bool
+  is_null(
+    T const &,
+    V)
+  noexcept
+  {
+    return false;
+  }

   template <typename T>
   inline
```

We use clang 9, clang 10, gcc 8 and MSVC 19.26.28806.0.

**Comment by rollbear** [comment]
There was only a little more compiler tickling required to make the MSVC tests pass (it compiled and worked, but produced some wrong violation messages.) Fix is availble on `master` now. Leaving the issue open until the fix is in a tagged release.

**Comment by reneme** [comment]
Awesome! Thanks for investigating that so swiftly. I'm looking forward to the next release then. :)

**Comment by rollbear** [comment]
Included in release v39
